<?xml version="1.0" encoding="GB2312" standalone="yes" ?>

<!-- just for com.sinosoft.utility.error.UserException -->

<!DOCTYPE UserExceptions [
  <!ELEMENT UserExceptions      (UserException+)>
  <!ELEMENT UserException       (Error*)>
  <!ATTLIST UserException ErrorCatalog CDATA #IMPLIED>
  <!ATTLIST UserException Description CDATA #IMPLIED>
  <!ELEMENT Error               (ErrorNo,ErrorMessage)>
  <!ELEMENT ErrorNo             (#PCDATA)>
  <!ELEMENT ErrorMessage        (#PCDATA)>
]>


<UserExceptions>
	<UserException ErrorCatalog="-1" Description="OS" />
	<UserException ErrorCatalog="-2" Description="NET" />
	<UserException ErrorCatalog="-3" Description="DATABASE">
		<Error>
			<ErrorNo>200</ErrorNo>
			<ErrorMessage>无满足条件的记录</ErrorMessage>
		</Error>
	</UserException>
	<UserException ErrorCatalog="-4" Description="MIDWARE" />
	<UserException ErrorCatalog="-5" Description="PROGRAM" />

	<UserException ErrorCatalog="-98" Description="APPLICATION">
		<Error>
			<ErrorNo>-1</ErrorNo>
			<ErrorMessage>填入值为空</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-2</ErrorNo>
			<ErrorMessage>校验无效</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-3</ErrorNo>
			<ErrorMessage>无相应的权限</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-4</ErrorNo>
			<ErrorMessage>查询无值</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-5</ErrorNo>
			<ErrorMessage>越界，记录数超过规定数目</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-6</ErrorNo>
			<ErrorMessage>服务返回串不满足规定节数</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-7</ErrorNo>
			<ErrorMessage>服务返回失败</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-996</ErrorNo>
			<ErrorMessage>没有定义的单证管理配置项</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1001</ErrorNo>
			<ErrorMessage>服务返回的数据没有Error对象信息</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1002</ErrorNo>
			<ErrorMessage>服务返回数据中的Error对象信息不符合定义格式</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1003</ErrorNo>
			<ErrorMessage>查询结果个数超过系统限制</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1004</ErrorNo>
			<ErrorMessage>调用服务的传递标志无效</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1005</ErrorNo>
			<ErrorMessage>方法调用参数为空</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1006</ErrorNo>
			<ErrorMessage>无法找到TuxedoConnectionFactory</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1007</ErrorNo>
			<ErrorMessage>参数值无效</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1008</ErrorNo>
			<ErrorMessage>没有提供保单号</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1009</ErrorNo>
			<ErrorMessage>没有提供立案号</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1010</ErrorNo>
			<ErrorMessage>用户的Session值为空</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1011</ErrorNo>
			<ErrorMessage>控制器无法流转到下一个页面</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1012</ErrorNo>
			<ErrorMessage>保费计算失败</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1013</ErrorNo> 
			<ErrorMessage>无满足条件的记录</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1014</ErrorNo>
			<ErrorMessage>没有提供批单号</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1015</ErrorNo>
			<ErrorMessage>生成单证号失败</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1016</ErrorNo>
			<ErrorMessage>没有获取相应险种信息</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1017</ErrorNo>
			<ErrorMessage>批单保存失败</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1018</ErrorNo>
			<ErrorMessage>没有报案信息</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1019</ErrorNo>
			<ErrorMessage>该报案已经立案，请在立案中拒赔案件</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1020</ErrorNo>
			<ErrorMessage>没有立案信息</ErrorMessage>
		</Error>
		<Error>
			<ErrorNo>-1021</ErrorNo>
			<ErrorMessage>立案已经结案</ErrorMessage>
		</Error>
    <Error>
      <ErrorNo>-1022</ErrorNo>
      <ErrorMessage>该报案已经拒赔，不能进行查勘登记</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1023</ErrorNo>
      <ErrorMessage>该报案已经立案，不能进行查勘登记</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1024</ErrorNo>
      <ErrorMessage>该报案已经登记过查勘</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1025</ErrorNo>
      <ErrorMessage>该报案已经立案</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1026</ErrorNo>
      <ErrorMessage>该报案没有查勘，不能立案</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1027</ErrorNo>
      <ErrorMessage>该报案已经拒赔，不能进行立案登记</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1028</ErrorNo>
      <ErrorMessage>该立案已经注销</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1029</ErrorNo>
      <ErrorMessage>该立案已经拒赔</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1030</ErrorNo>
      <ErrorMessage>该立案已经赔付</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1031</ErrorNo>
      <ErrorMessage>该立案已经做了预赔</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1032</ErrorNo>
      <ErrorMessage>该立案已经做了实赔</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1033</ErrorNo>
      <ErrorMessage>该立案没有理赔车辆,无法进行修理换件定损处理</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1034</ErrorNo>
      <ErrorMessage>立案已录入修理换件定损清单</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1035</ErrorNo>
      <ErrorMessage>该立案的修理换件定损清单不存在</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1036</ErrorNo>
      <ErrorMessage>该赔案为互碰自赔案,不能录入财产定损</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1037</ErrorNo>
      <ErrorMessage>该立案已录入财产定损</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1038</ErrorNo>
      <ErrorMessage>立案的财产定损不存在</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1039</ErrorNo>
      <ErrorMessage>该立案已录入人员定损</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1040</ErrorNo>
      <ErrorMessage>立案的人员定损不存在</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1041</ErrorNo>
      <ErrorMessage>该赔案为互碰自赔案,不能录入人员定损清单</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1042</ErrorNo>
      <ErrorMessage>案件中还有未通过核赔的预赔</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1043</ErrorNo>
      <ErrorMessage>案件中还有未通过核赔的计算书</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1044</ErrorNo>
      <ErrorMessage>案件没有计算书</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1045</ErrorNo>
      <ErrorMessage>保单没有进行核保,不能收费登记</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1046</ErrorNo>
      <ErrorMessage>保单已注销,不能收费登记</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1047</ErrorNo>
      <ErrorMessage>批单没有进行核批,不能收费登记</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1048</ErrorNo>
      <ErrorMessage>没有进行核赔,不能付费登记</ErrorMessage>
    </Error>  
    <Error>
      <ErrorNo>-1049</ErrorNo>
      <ErrorMessage>批单没有进行核批,不能付费登记</ErrorMessage>
    </Error>  
    <Error>
      <ErrorNo>-1050</ErrorNo>
      <ErrorMessage>承保时相关保单从未进行收费保单主表登记</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1051</ErrorNo>
      <ErrorMessage>没有进行核赔,不能付费登记</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1052</ErrorNo>
      <ErrorMessage>保单没有进行核保,不能付费登记</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1053</ErrorNo>
      <ErrorMessage>未找到应退的优惠信息</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1054</ErrorNo>
      <ErrorMessage>未找到案后费用信息</ErrorMessage>
    </Error>                       
    <Error>
      <ErrorNo>-1055</ErrorNo>
      <ErrorMessage>该报案经查勘认定不属于保险责任,不能立案</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1056</ErrorNo>
      <ErrorMessage>该立案已经登记过担保函</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1057</ErrorNo>
      <ErrorMessage>没有此反担保函号</ErrorMessage>
    </Error>    
    <Error>
      <ErrorNo>-1058</ErrorNo>
      <ErrorMessage>该立案已经登记过查勘</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-1059</ErrorNo>
      <ErrorMessage>只有首次批改保单才可以做终保日期的批改</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-2001</ErrorNo>
      <ErrorMessage>单证类型查询失败</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-2002</ErrorNo>
      <ErrorMessage>没有费率类型</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-2003</ErrorNo>
      <ErrorMessage>单证与流水号类型不一致</ErrorMessage>
    </Error>
		<Error>
			<ErrorNo>-2004</ErrorNo>
			<ErrorMessage>此保单已经全单退保，请注意出险日期!</ErrorMessage>
		</Error>       
		<Error>
			<ErrorNo>-2005</ErrorNo>
			<ErrorMessage>此保单已经满期退保，不能再做赔案!</ErrorMessage>
		</Error>       
		<Error>
			<ErrorNo>-2006</ErrorNo>
			<ErrorMessage>此保单已经注销，不能再做赔案!</ErrorMessage>
		</Error>       
		<Error>
			<ErrorNo>-2007</ErrorNo>
			<ErrorMessage>此保单还未通过核保，不能做赔案!</ErrorMessage>
		</Error>       
		<Error>
			<ErrorNo>-2008</ErrorNo>
			<ErrorMessage>此立案号与当前登录险种不符!</ErrorMessage>
		</Error>       		
		<Error>
			<ErrorNo>-2009</ErrorNo>
			<ErrorMessage>此关联单号与当前登录险种不符!</ErrorMessage>
		</Error>       		
		<Error>
			<ErrorNo>-2010</ErrorNo>
			<ErrorMessage>该关联担保函与当前担保函类型不匹配!</ErrorMessage>
		</Error>       		
		<Error>
			<ErrorNo>-2011</ErrorNo>
			<ErrorMessage>此保单已经终止合同，不能再做赔案!</ErrorMessage>
		</Error>       	
		
		<Error>
			<ErrorNo>-2012</ErrorNo>
			<ErrorMessage>该立案号不存在!</ErrorMessage>
		</Error>       		
		<Error>
			<ErrorNo>-2013</ErrorNo>
			<ErrorMessage>该立案没有拒赔，没有拒赔通知书!</ErrorMessage>
		</Error>       			
		<Error>
			<ErrorNo>-2014</ErrorNo>
			<ErrorMessage>该单证不能取消复核!</ErrorMessage>
		</Error>       			
		<Error>
			<ErrorNo>-2015</ErrorNo>
			<ErrorMessage>此投保单已经转入保单库,请先删除保单!</ErrorMessage>
		</Error>
		<Error>
		  <ErrorNo>-2016</ErrorNo>
			<ErrorMessage>已经做过收付费，不能核保、核赔作废!</ErrorMessage>
		</Error>        	
        		<Error>
		  <ErrorNo>-2017</ErrorNo>
			<ErrorMessage>超过了报案到立案之间的时间期限!</ErrorMessage>
		</Error>        
		<Error>
		  <ErrorNo>-2018</ErrorNo>
			<ErrorMessage>保单存在未核批通过的批单!</ErrorMessage>
		</Error>
		<!--add by mozhanfeng begin ,20050228,shenzhen,DACC20050225-03:限制只有一张没有结案的赔款计算书-->
		<Error>
			<ErrorNo>-2019</ErrorNo>
			<ErrorMessage>一个案件下赔款计算书只能做一张!</ErrorMessage>
		</Error>					
		<!--add by mozhanfeng end ,20050228,shenzhen,DACC20050225-03-->			
		<!--add by dongyanqi begin ,20050531-->
		<Error>
			<ErrorNo>-2020</ErrorNo>
			<ErrorMessage>新增个人客户身份证号码不能重复,请点击鼠标右键,然后点击后退返回客户信息录入页面.</ErrorMessage>
		</Error>	
		<Error>
			<ErrorNo>-2021</ErrorNo>
			<ErrorMessage>新增企业客户中文名称不能重复,请点击鼠标右键,然后点击后退返回客户信息录入页面.</ErrorMessage>
		</Error>		
		<Error>
        <ErrorNo>-4008</ErrorNo>
        <ErrorMessage>分保单已经复核,不能再复核</ErrorMessage>
      </Error>
  	<Error>
		  <ErrorNo>-4009</ErrorNo>
			<ErrorMessage>平台交互出错</ErrorMessage>
		</Error>  
		<!--add by dongyanqi end ,20050531 -->				
	</UserException>
	<UserException ErrorCatalog="-99" Description="OTHER">
	</UserException>
</UserExceptions>
